code_version: v7.0
group_name: ''

llm: 
  path: grok-3-mini
  backend: transformers
  is_api: true
  render: false
  temperature: 0.0
  top_p: 1.0

mix_llm: [] # disable

seed: 42
debug: false

# Ideally we would only need to change the following two lines to run a different experiments
  

defaults:
- experiment: basic


hydra:
  run:
    dir: ./outputs/${uuid:}
  searchpath:
    - ./simulation/scenarios/fishing/conf
    - ./simulation/scenarios/sheep/conf
    - ./simulation/scenarios/pollution/conf